### ISSUE TITLE
Data Tables

### ISSUE THREAD

**Issue by aramiz84** [aramiz84/Aramiz.net#2]
As an admin I want to be able store data in a database.

**Acceptance Criteria:** 
- [ ] Can I store data for page About?
- [ ] Can I store data for page Projects?
- [ ] Can I store data for page Main?

**Tasks:**
- [ ] Create Database
- [ ] Create Table About
- [ ] Create Table Project
- [ ] Create Table Main
