### ISSUE TITLE
Add jwt security of project rest api call post for

### ISSUE THREAD

**Issue by aramiz84** [aramiz84/Aramiz.net#21]
As an admin I want to be able login before add project entites in the azure storage table. Must validate user have permission or redirect user to login page. Must reponse back if user got access denied. 

**Requirement:**
- [ ] Learn Azure Storage Table security best practices
- [ ] Learn Azure Functions security best practies

**Acceptance Criteria:**
- [ ] Can a do rest api method PUT and update a project entity?
- [ ] Is Request body of type json?
- [ ] Is validation of empty or wrong URL project entity id? Should returen?

**Tasks:**
- [ ] Create Azure Function with rest method PUT
