### ISSUE TITLE
a

### ISSUE THREAD

**Issue by aramiz84** [aramiz84/Aramiz.net#23]
As an admin I want to be able login before add project entites in the azure storage table. Must validate user have permission or redirect user to login page. Must reponse back if user got access denied. 

**Requirement:**
- [ ] #21

**Acceptance Criteria:**
- [ ] Can I add project entites without to be redirect first to login page? 
- [ ] Is Security of type jwt?
- [ ] Is login request going through access management azure b2c service with single tenant approach?

**Tasks:**
- [ ] Add Azure Function login 
- [ ] Add login function in CreateProjects function to validate permission
