### ISSUE TITLE
Page Routing

### ISSUE THREAD

**Issue by aramiz84** [aramiz84/Aramiz.net#7]
As a visitor I want to go to different pages to have more look in Emil's Portfolio and what is about. I want to go to Main, About, Contact and Projects Page.

**Acceptance Criteria:**
- [x] Can I browse to Main, About, Contact and Projects pages?

**Tasks:**
- [x] Create Main Routing
- [x] Create About Routing
- [x] Create Projects Routing
- [x] Create Contact Routing
