### ISSUE TITLE
Page Admin Routing

### ISSUE THREAD

**Issue by aramiz84** [aramiz84/Aramiz.net#8]
As an admin I want to sign in and sign out to an admin page and redirect to admin landing page.

**Requirements:**
- [ ] Learn best practices to build admin route

**Acceptance Criteria:**
- [ ] Can I browse to Sign in, Sign Out and Admin pages?

**Tasks:**
- [x] Create Sign In Routing
- [ ] Create Sign Out Routing
- [ ] Create Admin Page Routing
