### ISSUE TITLE
Api Routing

### ISSUE THREAD

**Issue by aramiz84** [aramiz84/Aramiz.net#9]
As a admin I want to able to create, edit and delete entries to a database in azure through a REST API call

**Acceptance Critera:**
- [ ] Does api calls able to go through https protocol?
- [ ] Can we do sub api calls?

**Tasks:**
- [ ] Create API Routing /api/
- [ ] Create API Subrouting /api/
